[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.7.0"
image = "0.24.5"
minimp4 = "0.1.0"
openh264 = "0.3.1"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "benchmark"
harness = false